version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: "lan-frontend"
    volumes:
      - ./frontend:/usr/src/app # for watching files
    ports:
      - "4200:4200"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: "lan-backend"
    volumes:
      - ./backend:/app # for watching files
    ports:
      - "5000:5000"
