version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    volumes:
      - ./frontend/src:/app/src # for watching files
    ports:
      - "4200:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend"
    volumes:
        - ./backend:/app # for watching files
    ports:
      - "5000:5000"